# Travelling Salesman Problem (TSP) on a rectangular grid 

### Objective function description

* Cities placed on a rectangular grid in $\mathbb{R}^n$, dimension given by $A, B \in \mathbb{N}$
* Assuming Euclidean distance the optimal tour has the length  
  * $A \cdot B + \sqrt{2} - 1$ if $A$ and $B$ are even numbers
  * $A \cdot B$ otherwise

### How to find optimal tour using heuristics?

Our success heavily depends on efficient solution encoding. Rather extreme, binary, representation would result in $2^{n^2}$ states. Let us consider an encoding using $(n-1)!$ states "only", as demonstrated on the following example with $A=3$,  $B=2$ grid:
  
<img src="img/tsp_example.png">

Tour (in green) starts in city 0 and ends 1, proceeding via 2, 4, 5, 3. This corresponds to encoded solution $(1, 2, 2, 1, 0)$, i.e. indices of the selected remaining cities in each step.

Notes:

* $n = A \cdot B$
* $\mathbf{a} = (0, 0, \ldots, 0)$ 
* $\mathbf{b} = (n-2, n-3, \ldots, 0)$
* $f^*$ quals to 
  * $A \cdot B + \sqrt{2} - 1$ if both $A$ and $B$ are even numbers
  * $A \cdot B$ otherwise
* **For serious TSP optimization you should use much more sophisticated approaches, e.g. the [Concorde](https://en.wikipedia.org/wiki/Concorde_TSP_Solver) algorithm**

# Example Implementation

You can find it in `src/objfun_tsp.py`, class `TSPGrid`.

Real-world demonstration follows:

In [1]:
# Import path to source directory (bit of a hack in Jupyter)
import sys
import os
pwd = %pwd
sys.path.append(os.path.join(pwd, os.path.join('..', 'src')))

# Ensure modules are reloaded on any change (very useful when developing code on the fly)
%load_ext autoreload
%autoreload 2

In [2]:
# Import extrenal librarires
import numpy as np

# Import our code
from heur_sg import ShootAndGo
from objfun_tsp import TSPGrid  # <-- our implementation of TSP

### ``TSPGrid(3, 2)`` demonstration

In [3]:
# initialization
tsp = TSPGrid(3, 2)

In [4]:
# random point generation
x = tsp.generate_point()
print(x)

[0 2 1 1 0]


In [5]:
# decode this solution (into list of visited cities)
cx = tsp.decode(x)
print(cx)

[0 1 4 3 5 2]


In [6]:
# what is the cost of such tour?
of_val = tsp.evaluate(x)
print(of_val)

8.06449510224598


In [7]:
# what is the cost of our example tour?
of_val = tsp.evaluate([1, 2, 2, 1, 0])
print(of_val)

6.0


In [7]:
# neighbourhood of x:
N = tsp.get_neighborhood(x, 1)
print(N)

[array([1, 2, 1, 1, 0]), array([0, 1, 1, 1, 0]), array([0, 3, 1, 1, 0]), array([0, 2, 0, 1, 0]), array([0, 2, 2, 1, 0]), array([0, 2, 1, 0, 0])]


In [8]:
# decoded neighbours and their objective function values
for xn in N:
    print('{} ({}) -> {:.4f}'.format(xn, tsp.decode(xn), tsp.evaluate(xn)))

[1 2 1 1 0] ([0 2 4 3 5 1]) -> 7.4142
[0 1 1 1 0] ([0 1 3 4 5 2]) -> 6.8284
[0 3 1 1 0] ([0 1 5 3 4 2]) -> 7.4142
[0 2 0 1 0] ([0 1 4 2 5 3]) -> 8.0645
[0 2 2 1 0] ([0 1 4 5 3 2]) -> 7.2361
[0 2 1 0 0] ([0 1 4 3 2 5]) -> 9.3006


**Carefully** mind the difference between encoded solution vector vs decoded city tour and meaning of such neighbourhood.

### TSP optimization using Random Shooting ($\mathrm{SG}_{0}$)

In [12]:
heur = ShootAndGo(tsp, maxeval=1000, hmax=0)
print(heur.search())

{'best_y': 6.0, 'best_x': array([0, 1, 2, 1, 0]), 'neval': 1, 'log_data': Empty DataFrame
Columns: []
Index: []}


# Assignments:

1. Try to find a better performing heuristic (to test TSP implementation on your own).
2. Can you improve heuristic performance using any 
   1. **better random point generator**?
   2. **better neighbourhood generator**?

Use performance measures of your choice, e.g. $FEO$.